name: tiktokmusic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.6
  path_provider: ^2.1.1
  dio: ^5.4.0
  gallery_saver: ^2.3.2
  ffmpeg_kit_flutter_full_gpl: ^6.0.3  # Use this instead of ffmpeg_kit_flutter
  just_audio: ^0.9.36
  provider: ^6.1.2
  audio_service: ^0.18.12
  audio_session: ^0.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_art.png
